# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    # runs-on: ubuntu-latest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ] # macos-latest] #, windows-latest ]
        python-version: [ '3.10', '3.11' ]
        include:
          - os: ubuntu-latest
            pip-cache: ~/.cache/pip
            poetry-cache: ~/.cache/pypoetry
            build: false
#          - os: macos-latest
#            pip-cache: ~/Library/Caches/pip
#            poetry-cache: ~/Library/Caches/pypoetry
          - os: windows-latest
            pip-cache: ~\AppData\Local\pip\Cache
            poetry-cache: ~\AppData\Local\pypoetry\Cache
            build: true

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }} # 3.10
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }} # "3.10" for run: if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov pyxdg
      if: ( ${{ matrix.build }} ) { pip install pywin32 pywin32-ctypes }
        pip list
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=15 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        python -m pytest tests/check_browsers.py
