# This workflow will publish to TestPyPI
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Publish to TestPyPI

on:
  push:
    tags:
      - '*'

jobs:
  testpypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip3 install -U pip setuptools poetry
      - name: Build package
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry config http-basic.testpypi ${{ secrets.PYPI_USER }} ${{ secrets.PYPI_PWD }}
          poetry build
      - name: Publish package
        run: |
          poetry publish -r testpypi